-- Check dq_testcases columns
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dq_testcases'
ORDER BY ORDINAL_POSITION;
GO

-- Check dq_checks columns
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dq_checks'
ORDER BY ORDINAL_POSITION;
GO
